### ISSUE TITLE
cdbsearch: "rate limit exceeded" appears to lead to KeyError: 'score'

### ISSUE THREAD

**Issue by robertnurnberg** [vondele/cdbexplore#22]
This happened in a long running call for `python cdbsearch.py --epd "3rr1k1/bpp2q2/p1pn1p1p/P1P3pb/1P1P4/4BN1P/2QN1PPK/2R1R3 b - - 0 26" >& /tmp/rn/vondele2_kibitzbonusg5c5.txt &`

I believe this was triggered by cdb being overwhelmed today after noob made some changes to the queue priorities.

In any case, the script should not crash.

Unfortunately, I am not clear at all what precisely happened here. But the final error seems to be a `"score"` KeyError. So should we guard for that in line 187? 

Log attached.

[vondele2_kibitzbonusg5c5.txt](https://github.com/vondele/cdbexplore/files/11491720/vondele2_kibitzbonusg5c5.txt)

**Comment by vondele** [comment]
This could explain #19 

I'm not sure it is directly related to "rate limit exceeded", but it could be. I think before we generically fix it, I think we should see what we get back as a json in the case of failure. Probably putting it in a try/except block that prints out what we got so we can see why our expectations are wrong.

**Comment by robertnurnberg** [comment]
As per https://discord.com/channels/435943710472011776/1101022188313772083/1108389974224687136 our assumptions in the code correspond what noob says the API really sends.

So could be some http error due to server overload? I am not sure how best to fix that/catch for.

**Comment by vondele** [comment]
sure, what I think happens here is just just some corrupted being sent (maybe somebody vi-ing the code on the production system). What I suggest is to put the entire code that interacts with cdb in some try/except block, and just print the data we received on error. Next time this happens we have more data we can use to decide what to do.

**Comment by robertnurnberg** [comment]
I believe this particular issue (the script crashing because of an unexpected json reply) is fixed by https://github.com/vondele/cdbexplore/pull/23.
