### ISSUE TITLE
[to discuss/observe] are we scoring too many unscored moves on cdb?

### ISSUE THREAD

**Issue by robertnurnberg** [vondele/cdbexplore#50]
Since the commit https://github.com/vondele/cdbexplore/commit/1b50e938aad3ec4161a3ce0e3c50908fd440f82d we score one unscored moves of a node that satisfies `depth > 15 + scoreCount`.

I attach a long running exploration of 1. g4 which at the most recent completed iteration shows
```
Search at depth  34
  score     :  137
  PV        :  d7d5 e2e3 b8c6 d2d4 e7e5 b1c3 c8e6 d4e5 c6e5 h2h3 h7h5 g1f3 e5f3 d1f3 h5g4 h3g4 e6g4 f3g2 h8h1 g2h1 g8f6 c1d2 d8d6 h1g2 e8c8 f2f3 g4d7 e1c1 g7g6 g2f2 d6b6 c1b1 d8e8 d2c1 f8c5 d1d3 b6d6 f2h4 e8e5 h4h8 e5e8 h8h4 e8e5 h4h8 e5e8
  queryall  :  10892806
  bf        :  1.61
  inflight  :  3.24
  chessdbq  :  2625738
  enqueued  :  627042
  unscored  :  336303
  date      :  2023-05-31T11:02:56.262387
  total time:  9 days, 15:48:44.73
  req. time :  317
  URL       :  https://chessdb.cn/queryc_en/?rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR_w_KQkq_-_moves_g2g4_d7d5_e2e3_b8c6_d2d4_e7e5_b1c3_c8e6_d4e5_c6e5_h2h3_h7h5_g1f3_e5f3_d1f3_h5g4_h3g4_e6g4_f3g2_h8h1_g2h1_g8f6_c1d2_d8d6_h1g2_e8c8_f2f3_g4d7_e1c1_g7g6_g2f2_d6b6_c1b1_d8e8_d2c1_f8c5_d1d3_b6d6_f2h4_e8e5_h4h8_e5e8_h8h4_e8e5_h4h8_e5e8
```
So the unscored moves make up almost half the positions that we enqueued for analysis. My gut feeling is that this is a bit too much. A possible remedy would be to change that constant `15` to a higher value, like `20`.

By the way, there are some other constants like that in the code. Should we group/list them at the start of the script for easy reference and commenting?

[g4_log.txt](https://github.com/vondele/cdbexplore/files/11624008/g4_log.txt)

**Comment by vondele** [comment]
I also had the feeling we're scoring a bit too many unscored moves. 

I would have to have a look exactly at the code again to understand a bit better what we do exactly. There might be a way to temper it a bit. It might not be unrelated to the fact that we actually visit nodes very often (i.e. queryall is large compared to chessdbq).

**Comment by robertnurnberg** [comment]
So, apart from mate proving (which we can ignore for this issue), we `search` exactly one unscored move from a position if it satisfies `depth > 15 + scoreCount`, or if `depth - 2 + (worstscore - bestscore) // self.evalDecay >= 0`. (The latter would mean that every unscored move gets assigned `newdepth=0`.

Note also that every move we count in `count_unscored` will automatically increase `count_enqueued` by 1.

So the ratio in that example is really 50:50 between unscored moves (some way higher up in the explored tree) and unknown positions that arise near the leafs due to mini-max guided exploration.

A bit too skewed, I think. So raising that constant from `15` to `20` or `25` could be a first step?

**Comment by robertnurnberg** [comment]
Just for completeness, I post a link to [discord](https://discord.com/channels/435943710472011776/1101022188313772083/1113852166189359144) where we discussed how to sieve unscored moves, i.e. how better to select which unscored move we search. IMO that question is somewhat related to this issue. Options discussed were:

1.  Using a local engine (as a last resort)
2.  Implementing some move ordering within cdbsearch, similarly to what is done in engines. E.g. based on history heuristics.

**Comment by robertnurnberg** [comment]
Yes, very interesting indeed. I believe it depends a lot on the kind of position that is searched. My gut feeling is that nearly every unscored leads to an enqueued. That is because these are generally _bad_ moves, and so the nodes they lead to are unlikely to be worked on by other threads.

For example, if the position searched is already very well explored on cdb, then for a very long time we will hardly enqueue any unknown positions, but from a certain depth onwards, our scoring of unscored moves will kick in. Moreover, if we have a position that leads to many fortress-like positions, where `|worstscore-bestscore|` is small, then once again we will search many unscored moves.

Maybe it would be helpful to add some more statistics, maybe in a type of debug branch? Of interest to me would be (a) the number of siblings an unscored move we score has on average and (b) what `worstscore-bestscore` is there on average. We could also report the % of unscored in terms of enqueued, that probably also in the main branch.

**Comment by robertnurnberg** [comment]
Note that I have updated the `extraStats` branch with the PR https://github.com/vondele/cdbexplore/pull/71.

If you want to see the original behaviour with it (showing many unscored moves with just one scored sibling being scored), you need to edit line 437 from
```python
        allowUnscored = len(scored_db_moves) > CDB_SIEVED
```
to
```python
        allowUnscored = True
```

**Comment by robertnurnberg** [comment]
I think this issue can now be closed. This is a sample output with https://github.com/vondele/cdbexplore/commit/06714b316408bc4eddb9b65cb6da872bae1628d2:

```
Search at depth  20
  cdb PV len:  68
  score     :  150
  PV        :  d7d5 h2h3 h7h5 g4h5 e7e5 c2c3 d8h4 h5h6 e5e4 h6g7 f8g7 b1a3 f7f5 d2d4 g8f6 e2e3 b8c6 d1c2 c8e6 g1e2 e8c8 e2g3 g7f8 c1d2 f6d7 b2b4 c8b8 e1c1 d7b6 c1b2 f8d6 c2c1 d8f8 b2a1 f5f4
  PV len    :  35
  max ply   :  81
  queryall  :  1496162
  bf        :  2.04
  chessdbq  :  251736 (16.83% of queryall)
  enqueued  :  6363
  unscored  :  42 (0.66% of enqueued)
  reprobed  :  3416 (1.36% of chessdbq)
  inflightQ :  317.45
  inflightR :  13.12
  cdb time  :  31
  date      :  2023-06-17T18:49:32.171574
  total time:  2:14:01.49
  URL       :  https://chessdb.cn/queryc_en/?rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR_w_KQkq_-_moves_g2g4_d7d5_h2h3_h7h5_g4h5_e7e5_c2c3_d8h4_h5h6_e5e4_h6g7_f8g7_b1a3_f7f5_d2d4_g8f6_e2e3_b8c6_d1c2_c8e6_g1e2_e8c8_e2g3_g7f8_c1d2_f6d7_b2b4_c8b8_e1c1_d7b6_c1b2_f8d6_c2c1_d8f8_b2a1_f5f4
```
